// create-bunium-app/templates/solid-ts/src/App.tsx
import { createSignal } from "solid-js";

export default function App() {
  const [count, setCount] = createSignal(0);

  return (
    <div style={{ "font-family": "sans-serif", padding: "2rem" }}>
      <h1>__PROJECT_NAME__</h1>
      <p>A bunium + Solid + TypeScript app.</p>
      <button type="button" onClick={() => setCount((c) => c + 1)}>
        count is {count()}
      </button>
    </div>
  );
}

// create-bunium-app/templates/react-ts/src/App.tsx
import { useState } from "react";

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <div style={{ fontFamily: "sans-serif", padding: "2rem" }}>
      <h1>__PROJECT_NAME__</h1>
      <p>A bunium + React + TypeScript app.</p>
      <button type="button" onClick={() => setCount((c) => c + 1)}>
        count is {count}
      </button>
    </div>
  );
}
