// create-bunium-app/templates/vue-js/src/App.vue
<script setup>
import { ref } from "vue";

// biome-ignore lint/correctness/noUnusedVariables: count is used in the template below; Biome doesn't cross-reference script-setup bindings with template usage.
const count = ref(0);
</script>

<template>
  <div style="font-family: sans-serif; padding: 2rem">
    <h1>__PROJECT_NAME__</h1>
    <p>A bunium + Vue + JavaScript app.</p>
    <button type="button" @click="count++">count is {{ count }}</button>
  </div>
</template>

// create-bunium-app/templates/solid-js/src/App.jsx
import { createSignal } from "solid-js";

export default function App() {
  const [count, setCount] = createSignal(0);

  return (
    <div style={{ "font-family": "sans-serif", padding: "2rem" }}>
      <h1>__PROJECT_NAME__</h1>
      <p>A bunium + Solid + JavaScript app.</p>
      <button type="button" onClick={() => setCount((c) => c + 1)}>
        count is {count()}
      </button>
    </div>
  );
}
